//! Interrupt driven example for the LPCXpresso55S28 demo board.
//!
//! This is a minimal implementation intended to demonstrate only the minimum
//! essential implementation, to clarify usage of the class driver.
//!
//! Uses the EVK's WM8904 DAC at 48KHz. Clock is generated by PLL0. Simple
//! proportional feedback is implemented.
//!
//! Packets from USB are placed in a `bbqueue`. They are consumed by the I2S
//! FIFO in the FLEXCOMM7 interrupt. This makes the implementation very sensitive
//! to interrupt::free critical sections (which are widely used in the USB bus driver)
#![no_main]
#![no_std]

#[cfg(all(feature = "usbfs", feature = "usbhs"))]
compile_error!("Choose one USB peripheral, usbfs and usbhs cannot be used together");

extern crate panic_probe;
#[defmt::panic_handler]
fn panic() -> ! {
    panic_probe::hard_fault()
}

use bbqueue::{
    nicknames::Churrasco,
    prod_cons::stream::{StreamConsumer, StreamProducer},
    traits::bbqhdl::BbqHandle,
};
use core::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use cortex_m_rt::entry;
use defmt::debug;
use defmt_rtt as _;
use hal::raw as pac;
use hal::{
    Syscon,
    drivers::{Timer, UsbBus, pins},
    prelude::*,
    time::Hertz,
};
use lpc55_hal as hal;
use pac::interrupt;
use usb_device::{
    bus::{self},
    device::{StringDescriptors, UsbDeviceBuilder, UsbVidPid},
};
use usbd_uac2::{
    self, AudioHandler, ClockSource, RangeEntry, TerminalConfig, UsbAudioClassConfig,
    UsbIsochronousFeedback, UsbSpeed, constants::FunctionCode, descriptors::ClockType,
};

use crate::hw::{I2sTx, blue_led, green_led, red_led};

mod hw;
mod wm8904;

const CODEC_I2C_ADDR: u8 = 0b0011010;
const FIFO_LENGTH: usize = 256; // frames
const MCLK_FREQ: u32 = 12288000;
const SAMPLE_RATE: u32 = 48000;
// USB microframe rate
#[cfg(feature = "usbhs")]
const USB_FRAME_RATE: usize = 8000;
#[cfg(feature = "usbfs")]
const USB_FRAME_RATE: usize = 1000;
type SampleType = (i32, i32);

const BYTES_PER_FRAME: usize = 8;
const QUEUE_BYTES: usize = FIFO_LENGTH * BYTES_PER_FRAME;
// We use bbqueue here for performance in the USB driver that runs almost entirely in interrupt free critical section.
static QUEUE: Churrasco<QUEUE_BYTES> = Churrasco::new();
// Used for feedback calculation of current fifo state
static PRODUCED: AtomicU32 = AtomicU32::new(0);
static CONSUMED: AtomicU32 = AtomicU32::new(0);

#[inline]
fn try_write_one_frame<T: BbqHandle>(
    cons: &mut StreamConsumer<T>,
    i2s: &pac::i2s7::RegisterBlock,
) -> bool {
    if let Ok(rgr) = cons.read() {
        if rgr.len() >= BYTES_PER_FRAME {
            let l = u32::from_le_bytes(rgr[0..4].try_into().unwrap());
            let r = u32::from_le_bytes(rgr[4..8].try_into().unwrap());

            i2s.fifowr.write(|w| unsafe { w.bits(l) });
            i2s.fifowr.write(|w| unsafe { w.bits(r) });

            // consume exactly one frame (8 bytes)
            rgr.release(BYTES_PER_FRAME);
            CONSUMED.fetch_add(BYTES_PER_FRAME as u32, Ordering::Relaxed);
            return true;
        } else {
            // Not enough bytes for a full frame: leave it in the queue.
            return false;
        }
    }
    false
}

#[interrupt]
fn FLEXCOMM7() {
    let i2s = unsafe { &*pac::I2S7::ptr() };
    // refill until fifo has >6 words
    let mut cons = QUEUE.stream_consumer();
    while i2s.fifostat.read().txlvl().bits() <= 6 {
        if !try_write_one_frame(&mut cons, i2s) {
            // No complete frame available: write silence to keep FIFO above threshold
            defmt::error!("underflow");
            red_led().toggle();
            i2s.fifowr.write(|w| unsafe { w.bits(0) });
            i2s.fifowr.write(|w| unsafe { w.bits(0) });
            break;
        }
    }
}

struct Audio<T: BbqHandle> {
    running: AtomicBool,
    i2s: I2sTx,
    producer: StreamProducer<T>,
}
impl<T: BbqHandle> Audio<T> {
    const RATES: [RangeEntry<u32>; 1] = [RangeEntry::new_fixed(SAMPLE_RATE)];
    fn start(&self) {
        self.running.store(true, Ordering::Relaxed);
        defmt::info!("playback starting, enabling interrupts");
        self.i2s.i2s.fifointenclr.write(|w| w.txlvl().set_bit());
        // FIFO trigger threshold = <= 6 entries
        self.i2s
            .i2s
            .fifotrig
            .modify(|_, w| unsafe { w.txlvl().bits(6).txlvlena().enabled() });
        // FIFO level interrupt enable
        self.i2s.i2s.fifointenset.modify(|_, w| w.txlvl().enabled());
        unsafe { pac::NVIC::unmask(pac::Interrupt::FLEXCOMM7) };
        green_led().on();
    }
    fn stop(&self) {
        // If we don't disable interrupts while stopped, we will underflow constantly and continuously refill the fifo with 0s
        // We could actually stop the I2S here, but sometimes that makes the DAC misbehave. The peripheral is configured to send
        // 0s when the FIFO is empty, so this is fine.
        self.running.store(true, Ordering::Relaxed);
        defmt::info!("playback stopped");
        pac::NVIC::mask(pac::Interrupt::FLEXCOMM7);
        green_led().off();
    }
}

impl<T: BbqHandle> ClockSource for Audio<T> {
    const CLOCK_TYPE: usbd_uac2::descriptors::ClockType = ClockType::InternalFixed;
    const SOF_SYNC: bool = false;
    fn sample_rate(&self) -> u32 {
        Self::RATES[0].min
    }
    fn sample_rates(
        &self,
    ) -> core::result::Result<&[usbd_uac2::RangeEntry<u32>], usbd_uac2::UsbAudioClassError> {
        Ok(&Self::RATES)
    }
    fn clock_validity(&self) -> core::result::Result<bool, usbd_uac2::UsbAudioClassError> {
        Ok(true)
    }
}
impl<T: BbqHandle, B: bus::UsbBus> AudioHandler<'_, B> for Audio<T> {
    fn alternate_setting_changed(&mut self, _terminal: usb_device::UsbDirection, alt_setting: u8) {
        // alt setting 0 means stopped
        match alt_setting {
            0 => self.stop(),
            1 => self.start(),
            _ => defmt::error!("unexpected alt setting {}", alt_setting),
        }
    }
    fn audio_data_rx(
        &mut self,
        ep: &usb_device::endpoint::Endpoint<'_, B, usb_device::endpoint::Out>,
    ) {
        // Buffer must fit one microframe's (125us @ HS, 1ms @ FS) of audio data
        // (based on how `usbd_uac2` sets up the descriptors), calculate that
        // size here.
        let mut buf =
            [0; (SAMPLE_RATE as usize / USB_FRAME_RATE + 1) * core::mem::size_of::<SampleType>()];
        let len = match ep.read(&mut buf) {
            Ok(len) => len,
            Err(_) => {
                defmt::error!("usb error in rx callback");
                return;
            }
        };
        let buf = &buf[..len];

        if let Ok(mut wg) = self.producer.grant_exact(buf.len()) {
            wg.copy_from_slice(buf);
            wg.commit(buf.len());
            PRODUCED.fetch_add(buf.len() as u32, Ordering::Relaxed);
        } else {
            blue_led().on();
            defmt::error!("overflowed bbq, asked {}", buf.len());
        }
    }

    /// Provide rate feedback to the host, so that it doesn't over- or underflow
    /// our queue. This implementation is not tuned.
    fn feedback(&mut self, nominal_rate: UsbIsochronousFeedback) -> Option<UsbIsochronousFeedback> {
        let target = FIFO_LENGTH as i32 / 2;

        let fill = PRODUCED
            .load(Ordering::Acquire)
            .wrapping_sub(CONSUMED.load(Ordering::Acquire)) as i32
            / BYTES_PER_FRAME as i32;

        let error = fill - target;
        // Clamp excursions.
        let (i, _f) = nominal_rate.parts();
        let error = error.clamp(-(i as i32 * 4), i as i32 * 4);

        let p = error << 8;

        let correction = -p;
        let nominal_v = nominal_rate.to_u32_12_13() as i32;

        let mut v = nominal_v + correction;

        // Clamp corrections
        v = v.clamp(nominal_v - (1 << 14), nominal_v + (1 << 14));

        // Note: this log will cause continuous underflows
        defmt::debug!("fill:{} err:{} fb:{=u32:x}", fill, error, v);

        Some(UsbIsochronousFeedback::new(v as u32))
    }
}

#[entry]
fn main() -> ! {
    let hal = hal::new();

    let mut anactrl = hal.anactrl;
    let mut pmc = hal.pmc;
    let mut syscon = hal.syscon;

    let mut gpio = hal.gpio.enabled(&mut syscon);
    let mut iocon = hal.iocon.enabled(&mut syscon);

    debug!("start");

    hw::init_leds(&mut iocon, &mut gpio);

    debug!("iocon");
    let usb0_vbus_pin = pins::Pio0_22::take()
        .unwrap()
        .into_usb0_vbus_pin(&mut iocon);
    let codec_i2c_pins = (
        pins::Pio1_20::take().unwrap().into_i2c4_scl_pin(&mut iocon),
        pins::Pio1_21::take().unwrap().into_i2c4_sda_pin(&mut iocon),
    );
    // We can initialize and iocon these, but there is no peripheral, so they do not get used
    let _codec_i2s_pins = (
        pins::Pio0_21::take().unwrap().into_spi7_sck_pin(&mut iocon),
        pins::Pio0_20::take().unwrap().into_i2s7_sda_pin(&mut iocon),
        pins::Pio0_19::take().unwrap().into_i2s7_ws_pin(&mut iocon),
        pins::Pio1_31::take().unwrap(), // MCLK
    );

    debug!("clocks");
    let clocks = hal::ClockRequirements::default()
        .system_frequency(96.MHz())
        .configure(&mut anactrl, &mut pmc, &mut syscon)
        .unwrap();
    let mut _delay_timer = Timer::new(
        hal.ctimer
            .0
            .enabled(&mut syscon, clocks.support_1mhz_fro_token().unwrap()),
    );
    // Start PLL0 at 24.576MHz as the audio clock. The FRO cannot evenly divide any common audio frequencies.
    hw::init_audio_pll();

    debug!("peripherals");

    let i2c_peripheral = hal
        .flexcomm
        .4
        .enabled_as_i2c(&mut syscon, &clocks.support_flexcomm_token().unwrap());
    let mut i2c_bus = I2cMaster::new(
        i2c_peripheral,
        codec_i2c_pins,
        Hertz::try_from(400.kHz()).unwrap(),
    );

    let i2s_peripheral = {
        let fc7 = hal.flexcomm.7.release();
        hw::init_i2s(fc7.0, fc7.2, &mut syscon)
    };

    #[cfg(feature = "usbhs")]
    let (usb_speed, usb_peripheral) = (
        UsbSpeed::High,
        hal.usbhs.enabled_as_device(
            &mut anactrl,
            &mut pmc,
            &mut syscon,
            &mut _delay_timer,
            clocks.support_usbhs_token().unwrap(),
        ),
    );
    #[cfg(feature = "usbfs")]
    let (usb_speed, usb_peripheral) = (
        UsbSpeed::Full,
        hal.usbfs.enabled_as_device(
            &mut anactrl,
            &mut pmc,
            &mut syscon,
            clocks.support_usbfs_token().unwrap(),
        ),
    );

    let usb_bus = UsbBus::new(usb_peripheral, usb0_vbus_pin);

    defmt::debug!("codec init");
    wm8904::init_codec(&mut i2c_bus);

    // let consumer_ref = FIFO_CONSUMER_STORE.init(consumer);
    // unsafe { FIFO_CONSUMER = consumer_ref as *mut _ };

    let mut audio = Audio {
        i2s: i2s_peripheral,
        producer: QUEUE.stream_producer(),
        running: AtomicBool::new(false),
    };

    let config = UsbAudioClassConfig::new(usb_speed, FunctionCode::IoBox, &mut audio)
        .with_output_config(TerminalConfig::builder().base_id(2).build());

    let mut uac2 = config.build(&usb_bus).unwrap();

    let mut usb_dev = UsbDeviceBuilder::new(&usb_bus, UsbVidPid(0x1209, 0xcc1d))
        .composite_with_iads()
        .strings(&[StringDescriptors::default()
            .manufacturer("Generic")
            .product("usbd_uac2 device")
            .serial_number("123456789")])
        .unwrap()
        .max_packet_size_0(64)
        .unwrap()
        .device_class(0xef)
        .device_sub_class(0x02)
        .device_protocol(0x01)
        .build();

    defmt::info!("main loop");

    loop {
        usb_dev.poll(&mut [&mut uac2]);
    }
}
