//! Interrupt driven example for the LPCXpresso55S28 demo board.
//!
//! This is a minimal implementation intended to demonstrate only the minimum
//! essential implementation, to clarify usage of the class driver.
//!
//! Uses the EVK's WM8904 CODEC at 48KHz. Clock is generated by PLL0. Simple
//! proportional feedback is implemented.
//!
//! Packets from USB are placed in a `bbqueue` (a lock free ring buffer). They
//! are consumed by the I2S FIFO in the FLEXCOMM7 interrupt. This makes the
//! implementation very sensitive to interrupt::free critical sections (which
//! are widely used in the USB bus driver), but it works well enough at 48k.
//!
//! Audio frames from the CODEC are placed in a separate `bbqueue` from the
//! FLEXCOMM6 interrupt handler. They're drained out to the USB host in the USB
//! callback context.
//!
//! LEDs:
//!   - Blue - audio under/overrun - note this toggles a bunch at playback stream startup
//!   - Red - recording stream running
//!   - Green - playback stream running
#![no_main]
#![no_std]

#[cfg(all(feature = "usbfs", feature = "usbhs"))]
compile_error!("Choose one USB peripheral, usbfs and usbhs cannot be used together");

extern crate panic_probe;
#[defmt::panic_handler]
fn panic() -> ! {
    panic_probe::hard_fault()
}

use bbqueue::{
    nicknames::Churrasco,
    prod_cons::stream::{StreamConsumer, StreamProducer},
    traits::bbqhdl::BbqHandle,
};
use core::sync::atomic::{AtomicU32, Ordering};
use cortex_m_rt::entry;
use defmt::{debug, error, info, warn};
use defmt_rtt as _;
use hal::raw as pac;
use hal::{
    Syscon,
    drivers::{Timer, UsbBus, pins},
    prelude::*,
    time::Hertz,
};
use lpc55_hal as hal;
use pac::interrupt;
use usb_device::{
    bus::{self},
    device::{StringDescriptors, UsbVidPid},
};
use usbd_uac2::{
    self, AudioHandler, ClockSource, RangeEntry, TerminalConfig, UsbAudioClassConfig,
    UsbIsochronousFeedback, UsbSpeed, constants::FunctionCode, descriptors::ClockType,
};

use crate::hw::{I2sHandles, blue_led, green_led, red_led};

mod hw;
mod wm8904;

// pid.codes test IDs
const USB_VID: u16 = 0x1209;
const USB_PID: u16 = 0x0001;
const USB_MANUFACTURER: &str = "usbd_uac2";
const USB_PRODUCT: &str = "interrupt example device";

const CODEC_I2C_ADDR: u8 = 0b0011010;
const FIFO_LENGTH: usize = 256; // frames
const MCLK_FREQ: u32 = 12288000;
const SAMPLE_RATE: u32 = 48000;
// USB microframe rate
#[cfg(feature = "usbhs")]
const USB_FRAME_RATE: usize = 8000;
#[cfg(feature = "usbfs")]
const USB_FRAME_RATE: usize = 1000;

const BYTES_PER_FRAME: usize = 8;
const QUEUE_BYTES: usize = FIFO_LENGTH * BYTES_PER_FRAME;

static QUEUE_AUDIO_OUT: Churrasco<QUEUE_BYTES> = Churrasco::new();
// Used for feedback calculation of current fifo state
static PRODUCED_OUT: AtomicU32 = AtomicU32::new(0);
static CONSUMED_OUT: AtomicU32 = AtomicU32::new(0);

static QUEUE_AUDIO_IN: Churrasco<QUEUE_BYTES> = Churrasco::new();
// Used for feedback calculation of current fifo state
static PRODUCED_IN: AtomicU32 = AtomicU32::new(0);
static CONSUMED_IN: AtomicU32 = AtomicU32::new(0);

/// Consume one audio output frame and send it to the I2S FIFO. If there's
/// insufficient data in the queue, return false without consuming what was
/// there.
#[inline]
fn try_consume_one_frame<T: BbqHandle>(
    cons: &mut StreamConsumer<T>,
    i2s: &pac::i2s7::RegisterBlock,
) -> bool {
    if let Ok(rgr) = cons.read() {
        if rgr.len() >= BYTES_PER_FRAME {
            let l = u32::from_le_bytes(rgr[0..4].try_into().unwrap());
            let r = u32::from_le_bytes(rgr[4..8].try_into().unwrap());

            i2s.fifowr.write(|w| unsafe { w.bits(l) });
            i2s.fifowr.write(|w| unsafe { w.bits(r) });

            // consume exactly one frame (8 bytes)
            rgr.release(BYTES_PER_FRAME);
            CONSUMED_OUT.fetch_add(BYTES_PER_FRAME as u32, Ordering::Relaxed);
            return true;
        } else {
            // Not enough bytes for a full frame: leave it in the queue.
            return false;
        }
    }
    false
}

/// Produce one audio input from from the I2S FIFO into the queue. If there's no
/// room in the queue, discard the sample and return false.
#[inline]
fn try_produce_one_frame<T: BbqHandle>(
    prod: &mut StreamProducer<T>,
    i2s: &pac::i2s6::RegisterBlock,
) -> bool {
    let l = i2s.fiford.read().rxdata().bits();
    let r = i2s.fiford.read().rxdata().bits();
    if let Ok(mut rgr) = prod.grant_exact(BYTES_PER_FRAME) {
        unsafe {
            let wp = rgr.as_mut_ptr();
            core::ptr::copy_nonoverlapping(&l as *const u32 as *const u8, wp, 4);
            core::ptr::copy_nonoverlapping(&r as *const u32 as *const u8, wp.add(4), 4);
        }
        rgr.commit(BYTES_PER_FRAME * 2);
        PRODUCED_IN.fetch_add(BYTES_PER_FRAME as u32, Ordering::Relaxed);
        true
    } else {
        // No space in the queue, discard the sample
        false
    }
}

/// I2S TX ISR. Consume frames until the FIFO is full. Only write full frames
/// (L+R) so we can't desync left/right.
#[interrupt]
fn FLEXCOMM7() {
    let i2s = unsafe { pac::I2S7::ptr().as_ref().unwrap() };
    // refill until fifo has >6 words
    let mut cons = QUEUE_AUDIO_OUT.stream_consumer();

    while i2s.fifostat.read().txlvl().bits() <= 6 {
        if !try_consume_one_frame(&mut cons, i2s) {
            // No complete frame available: write silence to keep FIFO above threshold
            // error!("tx queue underflow");
            blue_led().toggle();
            i2s.fifowr.write(|w| unsafe { w.bits(0) });
            i2s.fifowr.write(|w| unsafe { w.bits(0) });
            break;
        }
    }
}

/// I2S RX ISR. Produce frames until the FIFO is empty (or has only a partial frame).
#[interrupt]
fn FLEXCOMM6() {
    let i2s = unsafe { pac::I2S6::ptr().as_ref().unwrap() };
    let mut prod = QUEUE_AUDIO_IN.stream_producer();
    while i2s.fifostat.read().rxlvl().bits() >= 2 {
        if !try_produce_one_frame(&mut prod, i2s) {
            blue_led().toggle();
            // error!("rx queue overflow");
            break;
        }
    }
}

/// Storage for Audio Class implementation state
struct Audio<T: BbqHandle> {
    i2s: I2sHandles,
    producer: StreamProducer<T>,
    consumer: StreamConsumer<T>,
}
impl<T: BbqHandle> Audio<T> {
    const RATES: [RangeEntry<u32>; 1] = [RangeEntry::new_fixed(SAMPLE_RATE)];
    /// Start audio playback. Clear anything in the FIFO, enable interrupts.
    fn start_audio_out(&self) {
        info!("playback starting, enabling interrupts");
        self.i2s.tx.fifocfg.modify(|_, w| w.emptytx().set_bit());
        self.i2s.tx.fifointenclr.write(|w| w.txlvl().set_bit());
        // TX FIFO trigger threshold = <= 6 entries
        self.i2s
            .tx
            .fifotrig
            .modify(|_, w| unsafe { w.txlvl().bits(6).txlvlena().enabled() });
        // TX FIFO level interrupt enable
        self.i2s.tx.fifointenset.write(|w| w.txlvl().enabled());

        // enable interrupts
        unsafe { pac::NVIC::unmask(pac::Interrupt::FLEXCOMM7) };

        green_led().on();
    }
    /// Start audio recording. Clear the FIFO, enable interrupts, and enable the peripheral.
    fn start_audio_in(&self) {
        info!("recording starting, enabling interrupts");

        self.i2s.rx.fifocfg.modify(|_, w| w.emptyrx().set_bit());
        self.i2s.rx.fifointenclr.write(|w| w.rxlvl().set_bit());
        // RX FIFO trigger threshold = >= 2 entries
        self.i2s
            .rx
            .fifotrig
            .modify(|_, w| unsafe { w.rxlvl().bits(1).rxlvlena().enabled() }); // 1 = generate when 2 pieces of data are in fifo
        // RX FIFO level interrupt enable
        self.i2s.rx.fifointenset.write(|w| w.rxlvl().enabled());
        // Start the peripheral
        self.i2s.rx.cfg1.modify(|_, w| w.mainenable().enabled());
        unsafe { pac::NVIC::unmask(pac::Interrupt::FLEXCOMM6) };
        red_led().on();
    }
    /// Stop audio playback. Disable interrupts, but leave the peripheral
    /// running. It is responsible for clocks, so is needed to clock the CODEC
    /// and input I2S. Leaving it running continuously is not harmful as the tx
    /// FIFO will empty and then emit 0s to the DAC.
    fn stop_audio_out(&self) {
        pac::NVIC::mask(pac::Interrupt::FLEXCOMM7);
        info!("playback stopped");
        green_led().off();
    }
    /// Stop audio recording. Disable the peripheral and mask any interrupts.
    fn stop_audio_in(&self) {
        self.i2s.rx.cfg1.modify(|_, w| w.mainenable().disabled());
        pac::NVIC::mask(pac::Interrupt::FLEXCOMM6);
        info!("recording stopped");
        red_led().off();
    }
}

/// Implement a fixed internal clock offering a single fixed audio rate, which is always valid.
impl<T: BbqHandle> ClockSource for Audio<T> {
    const CLOCK_TYPE: usbd_uac2::descriptors::ClockType = ClockType::InternalFixed;
    const SOF_SYNC: bool = false;
    fn sample_rate(&self) -> u32 {
        Self::RATES[0].min
    }
    fn sample_rates(
        &self,
    ) -> core::result::Result<&[usbd_uac2::RangeEntry<u32>], usbd_uac2::UsbAudioClassError> {
        Ok(&Self::RATES)
    }
    fn clock_validity(&self) -> core::result::Result<bool, usbd_uac2::UsbAudioClassError> {
        Ok(true)
    }
}
/// Implement the main audio handlers. This is a very naive implementation that
/// doesn't handle edge cases properly. For example, while altSetting=1
/// indicates the host expects to be able to emit audio data to the endpoint, it
/// does not indicate that the stream has started.
impl<T: BbqHandle, B: bus::UsbBus> AudioHandler<'_, B> for Audio<T> {
    /// On an alt setting change, start or stop the related audio pipeline. This
    /// behaviour should be replaced by a state machine with at least an 'armed
    /// but no data yet' state for playback.
    fn alternate_setting_changed(&mut self, terminal: usb_device::UsbDirection, alt_setting: u8) {
        match (terminal, alt_setting) {
            (usb_device::UsbDirection::Out, 0) => self.stop_audio_out(),
            (usb_device::UsbDirection::Out, 1) => self.start_audio_out(),
            (usb_device::UsbDirection::In, 0) => self.stop_audio_in(),
            (usb_device::UsbDirection::In, 1) => self.start_audio_in(),
            _ => error!("unexpected alt setting {} on {}", alt_setting, terminal),
        }
    }
    /// Receive audio data from USB. If we can, queue it into the output queue which will be drained by the ISR.
    fn audio_data_rx(
        &mut self,
        ep: &usb_device::endpoint::Endpoint<'_, B, usb_device::endpoint::Out>,
    ) {
        // Buffer must fit one microframe's (125us @ HS, 1ms @ FS) of audio data
        // (based on how `usbd_uac2` sets up the descriptors), calculate that
        // size here.
        let mut buf = [0; (SAMPLE_RATE as usize / USB_FRAME_RATE + 1) * BYTES_PER_FRAME];
        let len = match ep.read(&mut buf) {
            Ok(len) => len,
            Err(_) => {
                error!("usb error in rx callback");
                return;
            }
        };
        let buf = &buf[..len];

        if let Ok(mut wg) = self.producer.grant_exact(buf.len()) {
            wg.copy_from_slice(buf);
            wg.commit(buf.len());
            PRODUCED_OUT.fetch_add(buf.len() as u32, Ordering::Relaxed);
        } else {
            blue_led().on();
            error!("overflowed bbq, asked {}", buf.len());
        }
    }

    /// Transmit audio data to USB. If we have data in the queue, write it to
    /// the endpoint in appropriately sized microframes
    fn audio_data_tx(
        &mut self,
        ep: &usb_device::endpoint::Endpoint<'_, B, usb_device::endpoint::In>,
    ) {
        const NOMINAL_SAMPLES: usize = SAMPLE_RATE as usize / USB_FRAME_RATE;
        const DRAINING: i32 = ((FIFO_LENGTH * 4) / 10) as i32;
        const FILLING: i32 = ((FIFO_LENGTH * 6) / 10) as i32;

        // Allocate space for one additional audio frame, in case the host is
        // running slower than us and we need to occasionally stuff an extra
        // frame.
        let mut buf = [0; (NOMINAL_SAMPLES + 1) * BYTES_PER_FRAME];

        let fill = PRODUCED_IN
            .load(Ordering::Acquire)
            .wrapping_sub(CONSUMED_IN.load(Ordering::Acquire)) as i32
            / BYTES_PER_FRAME as i32;

        // Decide how many samples to write based on fill, this is how we deal with clock slippage.
        //  Draining (<40%) -> 1 fewer
        //  Filling (>50%) -> 1 more
        //  Nominal -> Nominal
        let samples = match fill {
            f if f < DRAINING => NOMINAL_SAMPLES - 1,
            f if f > FILLING => NOMINAL_SAMPLES + 1,
            _ => NOMINAL_SAMPLES,
        };
        let mut written = 0;
        let mut woff = 0usize;

        while written < samples {
            let Ok(rgr) = self.consumer.read() else {
                // warn!("underflowed IN queue, wrote {} of {}", written, samples);
                break;
            };

            let available_frames = rgr.len() / BYTES_PER_FRAME;

            if available_frames == 0 {
                break;
            }

            let to_copy = (samples - written).min(available_frames);
            let bytes = to_copy * BYTES_PER_FRAME;

            buf[woff..woff + bytes].copy_from_slice(&rgr[..bytes]);

            woff += bytes;
            rgr.release(bytes);
            written += to_copy;
            CONSUMED_IN.fetch_add(to_copy as u32, Ordering::Relaxed);
        }

        if let Err(e) = ep.write(&buf[..written * BYTES_PER_FRAME]) {
            warn!("Error writing to IN EP: {:?}", e);
        }
    }

    /// Provide rate feedback to the host, so that it doesn't over- or underflow
    /// our queue. This implementation is not tuned and without an I term is
    /// pretty unstable, but works fine.
    fn feedback(&mut self, nominal_rate: UsbIsochronousFeedback) -> Option<UsbIsochronousFeedback> {
        let target = FIFO_LENGTH as i32 / 2;

        let fill = PRODUCED_OUT
            .load(Ordering::Acquire)
            .wrapping_sub(CONSUMED_OUT.load(Ordering::Acquire)) as i32
            / BYTES_PER_FRAME as i32;

        let error = fill - target;
        // Clamp excursions.
        let (i, _f) = nominal_rate.parts();
        let error = error.clamp(-(i as i32 * 4), i as i32 * 4);

        let p = error << 8;

        let correction = -p;
        let nominal_v = nominal_rate.to_u32_12_13() as i32;

        let mut v = nominal_v + correction;

        // Clamp corrections
        v = v.clamp(nominal_v - (1 << 14), nominal_v + (1 << 14));

        // Note: this log will cause continuous underflows
        debug!("fill:{} err:{} fb:{=u32:x}", fill, error, v as u32);

        Some(UsbIsochronousFeedback::new(v as u32))
    }
}

#[entry]
fn main() -> ! {
    let hal = hal::new();

    let mut anactrl = hal.anactrl;
    let mut pmc = hal.pmc;
    let mut syscon = hal.syscon;

    let mut gpio = hal.gpio.enabled(&mut syscon);
    let mut iocon = hal.iocon.enabled(&mut syscon);

    debug!("start");

    hw::init_leds(&mut iocon, &mut gpio);

    debug!("iocon");
    let usb0_vbus_pin = pins::Pio0_22::take()
        .unwrap()
        .into_usb0_vbus_pin(&mut iocon);
    let codec_i2c_pins = (
        pins::Pio1_20::take().unwrap().into_i2c4_scl_pin(&mut iocon),
        pins::Pio1_21::take().unwrap().into_i2c4_sda_pin(&mut iocon),
    );
    // We can initialize and iocon these, but there is no peripheral driver, so the variables do not get used
    let _codec_i2s_pins = (
        pins::Pio0_21::take().unwrap().into_spi7_sck_pin(&mut iocon),
        pins::Pio0_20::take().unwrap().into_i2s7_sda_pin(&mut iocon),
        pins::Pio0_19::take().unwrap().into_i2s7_ws_pin(&mut iocon),
        pins::Pio1_13::take().unwrap().into_i2s6_sda_pin(&mut iocon),
        pins::Pio1_31::take().unwrap(), // MCLK
    );

    debug!("clocks");
    let clocks = hal::ClockRequirements::default()
        .system_frequency(96.MHz())
        .configure(&mut anactrl, &mut pmc, &mut syscon)
        .unwrap();
    let mut _delay_timer = Timer::new(
        hal.ctimer
            .0
            .enabled(&mut syscon, clocks.support_1mhz_fro_token().unwrap()),
    );
    // Start PLL0 at 24.576MHz as the audio clock. The FRO cannot evenly divide any common audio frequencies.
    hw::init_audio_pll();

    debug!("peripherals");

    let i2c_peripheral = hal
        .flexcomm
        .4
        .enabled_as_i2c(&mut syscon, &clocks.support_flexcomm_token().unwrap());
    let mut i2c_bus = I2cMaster::new(
        i2c_peripheral,
        codec_i2c_pins,
        Hertz::try_from(400.kHz()).unwrap(),
    );

    let i2s_peripheral = {
        let fc6 = hal.flexcomm.6.release();
        let fc7 = hal.flexcomm.7.release();

        hw::init_i2s(fc7.0, fc7.2, fc6.0, fc6.2, &mut syscon)
    };

    debug!("usb");
    #[cfg(feature = "usbhs")]
    let (usb_speed, usb_peripheral) = (
        UsbSpeed::High,
        hal.usbhs.enabled_as_device(
            &mut anactrl,
            &mut pmc,
            &mut syscon,
            &mut _delay_timer,
            clocks.support_usbhs_token().unwrap(),
        ),
    );
    #[cfg(feature = "usbfs")]
    let (usb_speed, usb_peripheral) = (
        UsbSpeed::Full,
        hal.usbfs.enabled_as_device(
            &mut anactrl,
            &mut pmc,
            &mut syscon,
            clocks.support_usbfs_token().unwrap(),
        ),
    );
    let usb_bus = UsbBus::new(usb_peripheral, usb0_vbus_pin);

    debug!("codec init");
    wm8904::init_codec(&mut i2c_bus);

    let mut audio = Audio {
        i2s: i2s_peripheral,
        producer: QUEUE_AUDIO_OUT.stream_producer(),
        consumer: QUEUE_AUDIO_IN.stream_consumer(),
    };

    let config = UsbAudioClassConfig::new(usb_speed, FunctionCode::IoBox, &mut audio)
        .with_output_config(TerminalConfig::builder().base_id(2).build())
        .with_input_config(TerminalConfig::builder().base_id(4).build());

    let mut uac2 = config.build(&usb_bus).unwrap();

    let mut usb_dev = usbd_uac2::builder(&usb_bus, UsbVidPid(USB_VID, USB_PID))
        .strings(&[StringDescriptors::default()
            .manufacturer(USB_MANUFACTURER)
            .product(USB_PRODUCT)])
        .unwrap()
        .max_packet_size_0(64) // Required to be 64 on HS, allowed on FS
        .unwrap()
        .build();

    debug!("main loop");

    loop {
        usb_dev.poll(&mut [&mut uac2]);
    }
}
