//! Interrupt driven example for the LPCXpresso55S28 demo board
//!
//! Uses the onboard WM8904 DAC at 48KHz. Clock is generated by PLL0. Simple PI feedback
//! is implemented.
//!
//! Packets from USB are placed a `heapless::spsc::Queue`. They are consumed
//! by the I2S FIFO in the FLEXCOMM7 interrupt.
#![no_main]
#![no_std]

#[cfg(all(feature = "usbfs", feature = "usbhs"))]
compile_error!("Choose one USB peripheral, usbfs and usbhs cannot be used together");

extern crate panic_probe;
#[defmt::panic_handler]
fn panic() -> ! {
    panic_probe::hard_fault()
}

use core::ptr::null_mut;
use core::sync::atomic::{AtomicBool, AtomicI32, Ordering};
use cortex_m_rt::entry;
use defmt::debug;
use defmt_rtt as _;
use hal::raw as pac;
use hal::{
    Syscon,
    drivers::{Timer, UsbBus, pins},
    prelude::*,
    time::Hertz,
};
use heapless::spsc::{Consumer, Producer, Queue};
use lpc55_hal::{self as hal};
use pac::interrupt;
use static_cell::StaticCell;
use usb_device::{
    bus::{self},
    device::{StringDescriptors, UsbDeviceBuilder, UsbVidPid},
    endpoint::IsochronousSynchronizationType,
};
use usbd_uac2::UsbIsochronousFeedback;
use usbd_uac2::{
    self, AudioClassConfig, RangeEntry, TerminalConfig, UsbAudioClass, UsbAudioClockImpl, UsbSpeed,
    constants::{FunctionCode, TerminalType},
    descriptors::{ChannelConfig, ClockType, FormatType1, LockDelay},
};

use crate::hw::I2sTx;

mod hw;
mod wm8904;

const CODEC_I2C_ADDR: u8 = 0b0011010;
const FIFO_LENGTH: usize = 256; // frames
const MCLK_FREQ: u32 = 12288000;
const SAMPLE_RATE: u32 = 48000; // example implementation runs okay at 48k but not 96k
type SampleType = (i32, i32);

struct Clock {}
impl Clock {
    const RATES: [RangeEntry<u32>; 1] = [RangeEntry::new_fixed(SAMPLE_RATE)];
}
impl UsbAudioClockImpl for Clock {
    const CLOCK_TYPE: usbd_uac2::descriptors::ClockType = ClockType::InternalFixed;
    const SOF_SYNC: bool = false;
    fn get_sample_rate(&self) -> core::result::Result<u32, usbd_uac2::UsbAudioClassError> {
        Ok(Clock::RATES[0].min)
    }
    fn get_rates(
        &self,
    ) -> core::result::Result<&[usbd_uac2::RangeEntry<u32>], usbd_uac2::UsbAudioClassError> {
        Ok(&Clock::RATES)
    }
    fn get_clock_validity(&self) -> core::result::Result<bool, usbd_uac2::UsbAudioClassError> {
        Ok(true)
    }
}

static FIFO_CONSUMER_STORE: StaticCell<Consumer<SampleType>> = StaticCell::new();
static mut FIFO_CONSUMER: *mut Consumer<SampleType> = null_mut();

#[interrupt]
fn FLEXCOMM7() {
    let i2s = unsafe { &*pac::I2S7::ptr() };

    // refil the buffer to 4 frames / 8 samples
    let fifo = unsafe { &mut *FIFO_CONSUMER };
    while i2s.fifostat.read().txlvl().bits() <= 6 {
        if let Some((l, r)) = fifo.dequeue() {
            i2s.fifowr.write(|w| unsafe { w.bits(l as u32) });
            i2s.fifowr.write(|w| unsafe { w.bits(r as u32) });
        } else {
            // Queue underflow
            defmt::error!("queue underflow");
            i2s.fifowr.write(|w| unsafe { w.bits(0) });
            i2s.fifowr.write(|w| unsafe { w.bits(0) });
        }
    }
}

struct Audio<'a> {
    running: AtomicBool,
    i2s: I2sTx,
    producer: Producer<'a, SampleType>,
    integrator: AtomicI32,
}
impl<'a> Audio<'a> {
    fn start(&self) {
        self.running.store(true, Ordering::Relaxed);
        defmt::info!("playback starting, enabling interrupts");
        self.i2s.i2s.fifointenclr.write(|w| w.txlvl().set_bit());
        // FIFO trigger threshold = <= 6 entries
        self.i2s
            .i2s
            .fifotrig
            .modify(|_, w| unsafe { w.txlvl().bits(6).txlvlena().enabled() });
        // FIFO level interrupt enable
        self.i2s.i2s.fifointenset.modify(|_, w| w.txlvl().enabled());
        unsafe { pac::NVIC::unmask(pac::Interrupt::FLEXCOMM7) };
    }
    fn stop(&self) {
        // If we don't disable interrupts while stopped, we will underflow constantly and continuously refill the fifo with 0s
        // We could actually stop the I2S here, but sometimes that makes the DAC misbehave. The peripheral is configured to send
        // 0s when the FIFO is empty, so this is fine.
        self.running.store(true, Ordering::Relaxed);
        defmt::info!("playback stopped");
        pac::NVIC::mask(pac::Interrupt::FLEXCOMM7);
    }
}
impl<'a, B: bus::UsbBus> UsbAudioClass<'a, B> for Audio<'_> {
    fn alternate_setting_changed(&mut self, _terminal: usb_device::UsbDirection, alt_setting: u8) {
        // alt setting 0 means stopped
        match alt_setting {
            0 => self.stop(),
            1 => self.start(),
            _ => defmt::error!("unexpected alt setting {}", alt_setting),
        }
    }
    fn audio_data_rx(
        &mut self,
        ep: &usb_device::endpoint::Endpoint<'a, B, usb_device::endpoint::Out>,
    ) {
        // Buffer must fit 1ms of audio data (based on how `usbd_uac2` sets up the descriptors), calculate that size here.
        let mut buf = [0; SAMPLE_RATE as usize / 1000 * core::mem::size_of::<SampleType>()];
        let len = match ep.read(&mut buf) {
            Ok(len) => len,
            Err(_) => {
                defmt::error!("usb error in rx callback");
                return;
            }
        };
        let buf = &buf[..len];
        // Translate the raw USB data into audio frames
        for sample in buf
            .chunks_exact(core::mem::size_of::<SampleType>())
            .map(|b| {
                // TODO: implement SampleType::from
                (
                    i32::from_le_bytes(b[..4].try_into().unwrap()),
                    i32::from_le_bytes(b[4..].try_into().unwrap()),
                )
            })
        {
            if self.producer.enqueue(sample).is_err() {
                defmt::error!("overflowed fifo, len: {}", self.producer.len());
            }
        }
    }

    /// Provide rate feedback to the host, so that it doesn't over- or underflow
    /// our queue.
    fn feedback(&mut self) -> Option<UsbIsochronousFeedback> {
        // Samples per USB interval (1ms)
        const FRAME_SAMPLES: i32 = SAMPLE_RATE as i32 / 1000;

        // Keep FIFO around half full, minus one USB packet worth
        const TARGET: i32 = FIFO_LENGTH as i32 / 2 - FRAME_SAMPLES;

        // 16.16 fixed-point nominal feedback value
        const NOMINAL: i32 = FRAME_SAMPLES << 16;
        const MAX_ERROR: i32 = FRAME_SAMPLES / 2;

        let queuelen = self.producer.len() as i32;

        let error = (queuelen - TARGET).clamp(-MAX_ERROR, MAX_ERROR);

        // slow down accumulation of I
        const I_ACCUM_DIV: i32 = 8;
        let i_delta = error / I_ACCUM_DIV;
        let integrator = self.integrator.fetch_add(i_delta, Ordering::Relaxed) + i_delta;

        // Integrator saturates at 1024xFRAME_SAMPLES
        let i_limit = FRAME_SAMPLES << 10;
        let integrator = integrator.clamp(-i_limit, i_limit);

        // Gains
        let p = error << 7;
        let i = integrator << 3;

        // Total correction in 16.16 space
        let correction = -(p + i);

        let v = NOMINAL + correction;

        defmt::debug!(
            "q:{} err:{} i:{} fb:{}",
            queuelen,
            error,
            integrator,
            v >> 16
        );

        Some(UsbIsochronousFeedback::new(v as u32))
    }
}

#[entry]
fn main() -> ! {
    let hal = hal::new();

    let mut anactrl = hal.anactrl;
    let mut pmc = hal.pmc;
    let mut syscon = hal.syscon;

    let mut gpio = hal.gpio.enabled(&mut syscon);
    let mut iocon = hal.iocon.enabled(&mut syscon);

    debug!("start");

    let mut red_led = pins::Pio1_6::take()
        .unwrap()
        .into_gpio_pin(&mut iocon, &mut gpio)
        .into_output_low(); // start turned off

    debug!("iocon");
    let usb0_vbus_pin = pins::Pio0_22::take()
        .unwrap()
        .into_usb0_vbus_pin(&mut iocon);
    let codec_i2c_pins = (
        pins::Pio1_20::take().unwrap().into_i2c4_scl_pin(&mut iocon),
        pins::Pio1_21::take().unwrap().into_i2c4_sda_pin(&mut iocon),
    );
    // We can initialize and iocon these, but there is no peripheral, so they do not get used
    let _codec_i2s_pins = (
        pins::Pio0_21::take().unwrap().into_spi7_sck_pin(&mut iocon),
        pins::Pio0_20::take().unwrap().into_i2s7_sda_pin(&mut iocon),
        pins::Pio0_19::take().unwrap().into_i2s7_ws_pin(&mut iocon),
        pins::Pio1_31::take().unwrap(), // MCLK
    );

    debug!("clocks");
    // Run the system clock at 96MHz. The lpc55-hal will run it from the FRO.
    let clocks = hal::ClockRequirements::default()
        .system_frequency(96.MHz())
        .configure(&mut anactrl, &mut pmc, &mut syscon)
        .unwrap();
    let mut _delay_timer = Timer::new(
        hal.ctimer
            .0
            .enabled(&mut syscon, clocks.support_1mhz_fro_token().unwrap()),
    );
    // Start PLL0 at 24.576MHz as the audio clock. The FRO cannot evenly divide any common audio frequencies.
    hw::init_audio_pll();

    debug!("peripherals");

    let i2c_peripheral = hal
        .flexcomm
        .4
        .enabled_as_i2c(&mut syscon, &clocks.support_flexcomm_token().unwrap());
    let mut i2c_bus = I2cMaster::new(
        i2c_peripheral,
        codec_i2c_pins,
        Hertz::try_from(400.kHz()).unwrap(),
    );

    let i2s_peripheral = {
        let fc7 = hal.flexcomm.7.release();
        hw::init_i2s(fc7.0, fc7.2, &mut syscon)
    };

    #[cfg(feature = "usbhs")]
    let usb_peripheral = hal.usbhs.enabled_as_device(
        &mut anactrl,
        &mut pmc,
        &mut syscon,
        &mut _delay_timer,
        clocks.support_usbhs_token().unwrap(),
    );
    #[cfg(feature = "usbfs")]
    let usb_peripheral = hal.usbfs.enabled_as_device(
        &mut anactrl,
        &mut pmc,
        &mut syscon,
        clocks.support_usbfs_token().unwrap(),
    );

    let usb_bus = UsbBus::new(usb_peripheral, usb0_vbus_pin);

    defmt::debug!("codec init");
    wm8904::init_codec(&mut i2c_bus);
    let queue = cortex_m::singleton!(
        : Queue<SampleType, FIFO_LENGTH>
        = Queue::new()
    )
    .unwrap();
    let (producer, consumer) = queue.split();

    let consumer_ref = FIFO_CONSUMER_STORE.init(consumer);
    unsafe { FIFO_CONSUMER = consumer_ref as *mut _ };

    let mut clock = Clock {};
    let mut audio = Audio {
        i2s: i2s_peripheral,
        producer,
        running: AtomicBool::new(false),
        integrator: AtomicI32::new(0),
    };

    let config = AudioClassConfig::new(UsbSpeed::High, FunctionCode::Other, &mut clock, &mut audio)
        .with_output_config(TerminalConfig::new(
            4,
            1,
            2,
            FormatType1 {
                bit_resolution: 32,
                bytes_per_sample: 4,
            },
            TerminalType::ExtLineConnector,
            ChannelConfig::default_chans(2),
            IsochronousSynchronizationType::Asynchronous,
            LockDelay::Milliseconds(10),
            None,
        ));

    let mut uac2 = config.build(&usb_bus).unwrap();

    let mut usb_dev = UsbDeviceBuilder::new(&usb_bus, UsbVidPid(0x1209, 0xcc1d))
        .composite_with_iads()
        .strings(&[StringDescriptors::default()
            .manufacturer("Generic")
            .product("usbd_uac2 device")
            .serial_number("123456789")])
        .unwrap()
        .max_packet_size_0(64)
        .unwrap()
        .device_class(0xef)
        .device_sub_class(0x02)
        .device_protocol(0x01)
        .build();

    defmt::info!("main loop");

    loop {
        usb_dev.poll(&mut [&mut uac2]);
        red_led.set_high().ok(); // Turn off
    }
}
